{
  # For OpenR open-sourced PRM: Math-psa
  RM: "math-psa-checkpoint",
  cot_task_desc: "",
  cot_examples: "",
  eot_token: null,
  eot_id: null,
  problem_format_str: "{question} {answer}",
  lm_step_tag: null,
  prm_step_tag: "\n\n\n\n\n"
}
